services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_container
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SA_PASSWORD}
    restart: always
  flask_app:
    container_name: flask_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      FLASK_APP: app.py
      FLASK_ENV: development
    depends_on:
      - mssql
    restart: always

  frontend:
    container_name: frontend_container
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - flask_app
    restart: always
